version: '3.8'

services:
  db:
    image: postgres:15
    container_name: python_flask_blog_pg
    restart: always
    environment:
      POSTGRES_USER: python-flask-blog
      POSTGRES_PASSWORD: python-flask-blog
      POSTGRES_DB: python-flask-blog-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
